// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from './routes/_404.tsx';
import * as $1 from './routes/_app.tsx';
import * as $2 from './routes/api/sessions/_middleware.ts';
import * as $3 from './routes/api/sessions/index.ts';
import * as $4 from './routes/api/sessions/logout.ts';
import * as $5 from './routes/api/sessions/password.ts';
import * as $6 from './routes/api/tasks/[id].ts';
import * as $7 from './routes/api/tasks/_middleware.ts';
import * as $8 from './routes/api/tasks/index.ts';
import * as $9 from './routes/api/users/refresh.ts';
import * as $10 from './routes/api/users/signin.ts';
import * as $11 from './routes/api/users/signup.ts';
import * as $12 from './routes/greet/[name].tsx';
import * as $13 from './routes/index.tsx';

const manifest = {
  routes: {
    './routes/_404.tsx': $0,
    './routes/_app.tsx': $1,
    './routes/api/sessions/_middleware.ts': $2,
    './routes/api/sessions/index.ts': $3,
    './routes/api/sessions/logout.ts': $4,
    './routes/api/sessions/password.ts': $5,
    './routes/api/tasks/[id].ts': $6,
    './routes/api/tasks/_middleware.ts': $7,
    './routes/api/tasks/index.ts': $8,
    './routes/api/users/refresh.ts': $9,
    './routes/api/users/signin.ts': $10,
    './routes/api/users/signup.ts': $11,
    './routes/greet/[name].tsx': $12,
    './routes/index.tsx': $13,
  },
  islands: {},
  baseUrl: import.meta.url,
};

export default manifest;
